# Generated by Django 4.1.3 on 2023-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='foodimage'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='foodimage'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='foodimage'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='foodimage'),
        ),
    ]
