# Generated by Django 4.1.3 on 2023-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_image_2_fooditem_image_3_fooditem_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage'),
        ),
    ]
