# Generated by Django 4.1.3 on 2023-03-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_total_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(),
        ),
    ]
